development:
  adapter: redis
  url: redis://:KEbjbMu4tCNvps6BXoNbfJ08KaQOHM9a@redis-16207.c85.us-east-1-2.ec2.cloud.redislabs.com:16207

test:
  adapter: redis
  url: redis://localhost:6379/1

production:
  adapter: redis
  url: redis://:KEbjbMu4tCNvps6BXoNbfJ08KaQOHM9a@redis-16207.c85.us-east-1-2.ec2.cloud.redislabs.com:16207
